from typing import List, Optional

from openenv.core.env_server.types import Action, Observation, State
from pydantic import Field


class ArgusAction(Action):
    """Typed action for the ARGUS environment."""

    missing_baseline: Optional[str] = Field(
        default=None,
        description="Exact name of the omitted baseline method for the easy task.",
    )
    cherry_picked_variant: Optional[str] = Field(
        default=None,
        description="Name of the suspiciously cherry-picked variant for the medium task.",
    )
    estimated_std_range: Optional[List[float]] = Field(
        default=None,
        description="Two-element list [low, high] describing the estimated standard deviation range.",
    )
    contamination_risk: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Estimated contamination risk score between 0.0 and 1.0 for the hard task.",
    )
    evidence: Optional[List[str]] = Field(
        default=None,
        description="Evidence signals supporting the contamination estimate.",
    )


class ArgusObservation(Observation):
    """Observation returned by the ARGUS environment."""

    task_name: str = Field(
        default="",
        description="Task identifier such as easy, medium, or hard.",
    )
    task_instruction: str = Field(
        default="",
        description="Instruction describing what the agent must determine.",
    )
    context: str = Field(
        default="",
        description="Research-paper-like context used for grading the answer.",
    )
    task_difficulty: str = Field(
        default="",
        description="Difficulty label for the current task.",
    )
    case_id: str = Field(
        default="",
        description="Deterministic scenario identifier for the current case.",
    )
    stage_index: int = Field(
        default=1,
        ge=1,
        description="1-based index of the current stage within the episode.",
    )
    stage_count: int = Field(
        default=1,
        ge=1,
        description="Total number of stages in the current episode.",
    )
    stage_name: str = Field(
        default="",
        description="Human-readable label for the current stage.",
    )
    stage_kind: str = Field(
        default="",
        description="Internal stage type used to select the grader.",
    )
    stage_weight: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Maximum reward weight available for the current stage.",
    )
    next_focus: str = Field(
        default="",
        description="What the next stage is expected to validate or reveal.",
    )
    episode_reward: float = Field(
        default=0.0,
        ge=0.0,
        description="Accumulated reward across the episode so far.",
    )
    feedback: str = Field(
        default="",
        description="Short feedback message generated by the grader for the latest action.",
    )


class ArgusState(State):
    """Extended state object for ARGUS episodes."""

    task_name: str = Field(default="", description="Current task key.")
    task_difficulty: str = Field(default="", description="Current task difficulty.")
    case_id: str = Field(default="", description="Scenario identifier for the active case.")
    episode_index: int = Field(default=0, ge=0, description="Zero-based episode counter.")
    task_cursor: int = Field(default=0, ge=0, description="Round-robin task cursor used when no task is supplied.")
    last_reward: float = Field(default=0.0, description="Reward produced by the most recent step.")
    episode_reward: float = Field(default=0.0, description="Total accumulated reward for the current episode.")
    stage_index: int = Field(default=0, ge=0, description="Zero-based stage pointer within the current episode.")
    stage_count: int = Field(default=0, ge=0, description="Total number of stages for the active episode.")
    stage_name: str = Field(default="", description="Human-readable label for the active stage.")
    stage_kind: str = Field(default="", description="Internal stage type used by the grader.")
    last_feedback: str = Field(default="", description="Latest grader feedback emitted during step().")
